//! Spirit's local operational modules are authored Rust.  Public wire data is
//! generated by the Ethos-owned signal crates and consumed as dependencies.
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
}
